name: Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install pnpm
      run: npm i -g pnpm
    - name: install and lint
      run: |
        pnpm install
        pnpm run lint
      env:
        CI: true
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install pnpm
      run: npm i -g pnpm
    - name: install and build
      run: |
        pnpm install
        pnpm run build
      env:
        CI: true
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install pnpm
      run: npm i -g pnpm
    - name: install and test
      run: |
        pnpm install
        pnpm run test
      env:
        CI: true
    - name: Upload coverage
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
      with:
        coverageCommand: pnpm run test
